puts "* set_option..."
set_option -vlog_std sysv
set_option -project_relative_includes 1
set_option -job pr_1 -add par
set_option -technology CYCLONEIV-E
set_option -part EP4CE115
set_option -package FI23
set_option -speed_grade -7
set_option -part_companion ""
set_option -use_fsm_explorer 0
set_option -top_module "fpgnix"
set_option -distributed_compile 1
set_option -hdl_strict_syntax 0
set_option -synthesis_strategy base
set_option -rw_check_on_ram 1
set_option -frequency auto
set_option -srs_instrumentation 1
set_option -write_verilog 1
set_option -write_vhdl 0
set_option -run_prop_extract 1
set_option -maxfan 30
set_option -disable_io_insertion 0
set_option -pipe 1
set_option -update_models_cp 0
set_option -retiming 0
set_option -no_sequential_opt 0
set_option -fix_gated_and_generated_clocks 1
set_option -quartus_version 18.1
set_option -symbolic_fsm_compiler 1
set_option -compiler_compatible 0
set_option -resource_sharing 1
set_option -multi_file_compilation_unit 1
set_option -auto_infer_blackbox 0
set_option -write_apr_constraint 1
