//                              Copyright (C) 2015-2020 by EnICS Labs

//                          01
//                        01 10
//                       1 10 010101010              1010     0101010    1010101
//                       1 10         0              1  0    10     0   0      1
//                       1   1010101010              1  0   01  01010  1   10101
//                        010                        1  0   0  10      1  0
//                      01  01            01010101   1  0  1  01       1  01
//                     10 01 1010101010  10       0  1  0  1  0        10  10
//                     1  01          0  1   10   0  1  0  1  0         0    1
//                     10   01010101010  1  01 1  0  1  0  1  0          10   0
//                      01010            1  0  1  0  1  0  1  0           01   1
//                      0101             1  0  1  0  1  0  1  01           10  1
//                     1    0            1  0  1  0  1  0   0  10           0  1
//                    0  10 01010101010  1  0  1  0  1  0   01  01010  10101   1
//                    0 0 0           0  1  0  1  0  1  0    10     0  1      01
//                    0 01  01010101010  1010  1010  1010     0101010  10101010
//                    0    1
//                     1010
//                               ------<< System-on-Chip Lab >>-------
//
//           This module is confidential and proprietary property of EnICS Labs and the possession or use
//                          of this file requires a written license from EnICS Labs.


// Title          : Memories ranges defines
// Project        : leo_i
// Generated by   : slavay
// Generated with : $PULP_ENV/src/ips/crg_legacy/scripts/common/matrix_address_parsing.py
// Created        : July 09 2020 at 21:51:51
// Description    : Address ranges defines for verification/software
// ----------------------------------------------------------------------------------------------------------- 

#ifndef AUTO_ADDR_H
#define AUTO_ADDR_H

#define MIN_PNX_UART_APB_S                0x1A100000
#define MAX_PNX_UART_APB_S                0x1A100FFF

#define MIN_PNX_GPIO_APB_S                0x1A101000
#define MAX_PNX_GPIO_APB_S                0x1A101FFF

#define MIN_PNX_SPI_APB_S                 0x1A102000
#define MAX_PNX_SPI_APB_S                 0x1A102FFF

#define MIN_PNX_TIMER_APB_S               0x1A103000
#define MAX_PNX_TIMER_APB_S               0x1A103FFF

#define MIN_PNX_EVENT_UNIT_APB_S          0x1A104000
#define MAX_PNX_EVENT_UNIT_APB_S          0x1A104FFF

#define MIN_PNX_I2C_APB_S                 0x1A105000
#define MAX_PNX_I2C_APB_S                 0x1A105FFF

#define MIN_PNX_INT_SOC_CTRL_APB_S        0x1A107000
#define MAX_PNX_INT_SOC_CTRL_APB_S        0x1A107FFF

#define MIN_PNX_DEBUG_IF_APB_S            0x1A110000
#define MAX_PNX_DEBUG_IF_APB_S            0x1A117FFF

#define MIN_PNX_PMM_IF_APB_S              0x1A200000
#define MAX_PNX_PMM_IF_APB_S              0x1A2FFFFF

#define MIN_TOP_RCG_APB_S                 0x1A300000
#define MAX_TOP_RCG_APB_S                 0x1A3003FF

#define MIN_GP_RF_APB_S                   0x1A301000
#define MAX_GP_RF_APB_S                   0x1A301FFF

#define MIN_FLL_CTRL_APB_S                0x1A302000
#define MAX_FLL_CTRL_APB_S                0x1A302FFF

#define MIN_RST_CTRL_APB_S                0x1A303000
#define MAX_RST_CTRL_APB_S                0x1A303FFF

#define MIN_DBG_UNIT_APB_S                0x1A304000
#define MAX_DBG_UNIT_APB_S                0x1A304FFF

#define MIN_TRNG_0_APB_S                  0x1A305000
#define MAX_TRNG_0_APB_S                  0x1A305FFF

#define MIN_TRNG_1_APB_S                  0x1A306000
#define MAX_TRNG_1_APB_S                  0x1A306FFF

#define MIN_TRNG_2_APB_S                  0x1A307000
#define MAX_TRNG_2_APB_S                  0x1A307FFF

#define MIN_TRNG_3_APB_S                  0x1A308000
#define MAX_TRNG_3_APB_S                  0x1A308FFF

#define MIN_TRNG_4_APB_S                  0x1A309000
#define MAX_TRNG_4_APB_S                  0x1A309FFF

#define MIN_TRNG_5_APB_S                  0x1A30A000
#define MAX_TRNG_5_APB_S                  0x1A30AFFF

#define MIN_TRNG_6_APB_S                  0x1A30B000
#define MAX_TRNG_6_APB_S                  0x1A30BFFF

#define MIN_TRNG_7_APB_S                  0x1A30C000
#define MAX_TRNG_7_APB_S                  0x1A30CFFF

#define MIN_TRNG_8_APB_S                  0x1A30D000
#define MAX_TRNG_8_APB_S                  0x1A30DFFF

#define MIN_TRNG_9_APB_S                  0x1A30E000
#define MAX_TRNG_9_APB_S                  0x1A30EFFF

#define MIN_TRNG_10_APB_S                 0x1A30F000
#define MAX_TRNG_10_APB_S                 0x1A30FFFF

#define MIN_TRNG_11_APB_S                 0x1A310000
#define MAX_TRNG_11_APB_S                 0x1A310FFF

#define MIN_PR80_APB_S                    0x1A311000
#define MAX_PR80_APB_S                    0x1A311FFF

#define MIN_AEAD0_APB_S                   0x1A312000
#define MAX_AEAD0_APB_S                   0x1A312FFF

#define MIN_AEAD1_APB_S                   0x1A313000
#define MAX_AEAD1_APB_S                   0x1A313FFF

#define MIN_WP_APB_S                      0x1A314000
#define MAX_WP_APB_S                      0x1A314FFF

#define MIN_EDRAM_APB_S                   0x1A320000
#define MAX_EDRAM_APB_S                   0x1A33FFFF

#endif // #ifndef AUTO_ADDR_H