$PULP_ENV/src/ips/crg_legacy/design/soc_building_blocks/hdl/apb2cbus.v
$PULP_ENV/src/ips/crg_legacy/design/soc_building_blocks/hdl/generic_clk_div.v
$PULP_ENV/src/ips/crg_legacy/design/soc_building_blocks/hdl/generic_fifo_crgn.v
$PULP_ENV/src/ips/crg_legacy/design/soc_building_blocks/hdl/generic_fifo_env_2prf_a128d32.v
$PULP_ENV/src/ips/crg_legacy/design/soc_building_blocks/hdl/generic_fifo_env_2prf_a256d24.v

$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_bscan_cell.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_chip_jtag.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_clk_buf.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_clk_clockgate_cust.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_clk_mx4.v
#$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_clk_nand2.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_clk_nor2.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_clk_or2.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_ff_arst.v
#$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_glitch_free_mux.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_lat.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_mx3.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_mx4.v
$PULP_ENV/src/ips/crg_legacy/design/dw_cells/hdl/crg_scan_ff.v
$PULP_ENV/src/ips/crg_legacy/design/dw_sync/hdl/crg_reset_cross.v
#$PULP_ENV/src/ips/crg_legacy/design/dw_sync/hdl/crg_sync2.v
$PULP_ENV/src/ips/crg_legacy/design/dw_sync/hdl/crg_sync2_arst_bus.v
#$PULP_ENV/src/ips/crg_legacy/design/dw_sync/hdl/crg_sync2n_arst.v
